/*
 Navicat Premium Data Transfer

 Source Server         : 34.126.123.190
 Source Server Type    : Oracle
 Source Server Version : 230000 (Oracle Database 23ai Enterprise Edition Release 23.0.0.0.0 - for Oracle Cloud and Engineered Systems)
 Source Host           : 34.126.123.190:1521
 Source Schema         : ADMIN

 Target Server Type    : Oracle
 Target Server Version : 230000 (Oracle Database 23ai Enterprise Edition Release 23.0.0.0.0 - for Oracle Cloud and Engineered Systems)
 File Encoding         : 65001

 Date: 31/10/2025 23:34:40
*/


-- ----------------------------
-- Table structure for TIME_DIMENSION
-- ----------------------------
DROP TABLE "ADMIN"."TIME_DIMENSION";
CREATE TABLE "ADMIN"."TIME_DIMENSION" (
  "DATE_TIME" DATE VISIBLE NOT NULL,
  "YEAR" NUMBER VISIBLE,
  "MONTH" NUMBER VISIBLE,
  "DAY" NUMBER VISIBLE,
  "HOUR" NUMBER(2,0) VISIBLE,
  "ID" NUMBER VISIBLE DEFAULT "ADMIN"."ISEQ$$_92780".nextval NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 10
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for SOURCE_DIMENSION
-- ----------------------------
DROP TABLE "ADMIN"."SOURCE_DIMENSION";
CREATE TABLE "ADMIN"."SOURCE_DIMENSION" (
  "ID" NUMBER VISIBLE DEFAULT "ADMIN"."ISEQ$$_92769".nextval NOT NULL,
  "SOURCE_NAME" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "SOURCE_URL" VARCHAR2(255 BYTE) VISIBLE,
  "DESCRIPTION" NVARCHAR2(2000) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 10
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for LOCATION_DIMENSION
-- ----------------------------
DROP TABLE "ADMIN"."LOCATION_DIMENSION";
CREATE TABLE "ADMIN"."LOCATION_DIMENSION" (
  "ID" NUMBER VISIBLE DEFAULT "ADMIN"."ISEQ$$_92777".nextval NOT NULL,
  "CITY" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "REGION" VARCHAR2(255 CHAR) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 10
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for GOLD_TYPE_DIMENSION
-- ----------------------------
DROP TABLE "ADMIN"."GOLD_TYPE_DIMENSION";
CREATE TABLE "ADMIN"."GOLD_TYPE_DIMENSION" (
  "ID" NUMBER VISIBLE DEFAULT "ADMIN"."ISEQ$$_92774".nextval NOT NULL,
  "TYPE_NAME" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "PURITY" VARCHAR2(50 BYTE) VISIBLE,
  "CATEGORY" VARCHAR2(100 BYTE) VISIBLE,
  "BRAND" VARCHAR2(255 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 10
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for GOLD_PRICE_FACT
-- ----------------------------
DROP TABLE "ADMIN"."GOLD_PRICE_FACT";
CREATE TABLE "ADMIN"."GOLD_PRICE_FACT" (
  "ID" NUMBER VISIBLE DEFAULT "ADMIN"."ISEQ$$_92782".nextval NOT NULL,
  "SOURCE_ID" NUMBER VISIBLE NOT NULL,
  "TYPE_ID" NUMBER VISIBLE NOT NULL,
  "LOCATION_ID" NUMBER VISIBLE NOT NULL,
  "TIME_ID" NUMBER VISIBLE NOT NULL,
  "BUY_PRICE" FLOAT(53) VISIBLE,
  "SELL_PRICE" FLOAT(53) VISIBLE,
  "UNIT" VARCHAR2(255 CHAR) VISIBLE,
  "RECORDED_AT" TIMESTAMP(6) VISIBLE DEFAULT SYSTIMESTAMP,
  "IS_DELETED" NUMBER(1,0) VISIBLE DEFAULT 0 NOT NULL,
  "RECORDED_BY" VARCHAR2(100 BYTE) VISIBLE,
  "IS_DELETE" NUMBER(1,0) VISIBLE DEFAULT 0
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 10
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Primary Key structure for table TIME_DIMENSION
-- ----------------------------
ALTER TABLE "ADMIN"."TIME_DIMENSION" ADD CONSTRAINT "SYS_C0014545" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table TIME_DIMENSION
-- ----------------------------
ALTER TABLE "ADMIN"."TIME_DIMENSION" ADD CONSTRAINT "SYS_C0014525" CHECK ("DATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ADMIN"."TIME_DIMENSION" ADD CONSTRAINT "SYS_C0014544" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table SOURCE_DIMENSION
-- ----------------------------
ALTER TABLE "ADMIN"."SOURCE_DIMENSION" ADD CONSTRAINT "SYS_C0014518" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table SOURCE_DIMENSION
-- ----------------------------
ALTER TABLE "ADMIN"."SOURCE_DIMENSION" ADD CONSTRAINT "SYS_C0014516" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ADMIN"."SOURCE_DIMENSION" ADD CONSTRAINT "SYS_C0014517" CHECK ("SOURCE_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table LOCATION_DIMENSION
-- ----------------------------
ALTER TABLE "ADMIN"."LOCATION_DIMENSION" ADD CONSTRAINT "SYS_C0014524" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table LOCATION_DIMENSION
-- ----------------------------
ALTER TABLE "ADMIN"."LOCATION_DIMENSION" ADD CONSTRAINT "SYS_C0014522" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ADMIN"."LOCATION_DIMENSION" ADD CONSTRAINT "SYS_C0014523" CHECK ("CITY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table GOLD_TYPE_DIMENSION
-- ----------------------------
ALTER TABLE "ADMIN"."GOLD_TYPE_DIMENSION" ADD CONSTRAINT "SYS_C0014521" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table GOLD_TYPE_DIMENSION
-- ----------------------------
ALTER TABLE "ADMIN"."GOLD_TYPE_DIMENSION" ADD CONSTRAINT "SYS_C0014519" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ADMIN"."GOLD_TYPE_DIMENSION" ADD CONSTRAINT "SYS_C0014520" CHECK ("TYPE_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table GOLD_PRICE_FACT
-- ----------------------------
ALTER TABLE "ADMIN"."GOLD_PRICE_FACT" ADD CONSTRAINT "SYS_C0014532" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table GOLD_PRICE_FACT
-- ----------------------------
ALTER TABLE "ADMIN"."GOLD_PRICE_FACT" ADD CONSTRAINT "SYS_C0014527" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ADMIN"."GOLD_PRICE_FACT" ADD CONSTRAINT "SYS_C0014528" CHECK ("SOURCE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ADMIN"."GOLD_PRICE_FACT" ADD CONSTRAINT "SYS_C0014529" CHECK ("TYPE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ADMIN"."GOLD_PRICE_FACT" ADD CONSTRAINT "SYS_C0014530" CHECK ("LOCATION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ADMIN"."GOLD_PRICE_FACT" ADD CONSTRAINT "SYS_C0014531" CHECK ("TIME_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ADMIN"."GOLD_PRICE_FACT" ADD CONSTRAINT "SYS_C0014547" CHECK ("IS_DELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table GOLD_PRICE_FACT
-- ----------------------------
ALTER TABLE "ADMIN"."GOLD_PRICE_FACT" ADD CONSTRAINT "FK_LOCATION" FOREIGN KEY ("LOCATION_ID") REFERENCES "ADMIN"."LOCATION_DIMENSION" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ADMIN"."GOLD_PRICE_FACT" ADD CONSTRAINT "FK_SOURCE" FOREIGN KEY ("SOURCE_ID") REFERENCES "ADMIN"."SOURCE_DIMENSION" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ADMIN"."GOLD_PRICE_FACT" ADD CONSTRAINT "FK_TYPE" FOREIGN KEY ("TYPE_ID") REFERENCES "ADMIN"."GOLD_TYPE_DIMENSION" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ADMIN"."GOLD_PRICE_FACT" ADD CONSTRAINT "GOLD_PRICE_FACT_TIME_DIMENSION_FK" FOREIGN KEY ("TIME_ID") REFERENCES "ADMIN"."TIME_DIMENSION" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
